---
- name: Instalar Docker
  ansible.builtin.dnf:
    name: docker
    state: present
    update_cache: true

- name: Habilitar y arrancar Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Añadir el usuario SSH al grupo docker
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Crear el directorio de plugins CLI de Docker
  ansible.builtin.file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: "0755"

- name: Instalar el plugin docker compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_cli_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: "0755"
